### ISSUE TITLE
use of existential type (*) is incompatible with babel-plugin-flow-react-proptypes

### ISSUE THREAD

**Issue by orenklein** [react-native-community/react-native-tab-view#113]
Even though it is not an error caused by react-native-tab-view package, it would be very appreciated for anyone using that plugin. 
babel-plugin-flow-react-proptypes throws an error on the Array<*> in PanResponderTypes.js file.
I don't know how necessary it is to use * instead of any type in that case. If it's not necessary, replacing it with any type is solving the problem.
Another approach could be to put 'no babel-plugin-flow-react-proptypes'; on top of the file.

**Comment by satya164** [comment]
We can add more specific type definition instead of `*`, but you should file a bug report in `babel-plugin-flow-react-proptypes` repo. It shouldn't even care about `PanResponderTypes.js` file. It doesn't have any React component in it and the types exported aren't part of the propType of any React components.

**Comment by orenklein** [comment]
I agree it is weird that it cares about PanResponderTypes.js file.
Anyway, I did file a bug report babel-plugin-flow-react-proptypes and it's been already solved, so I'm closing this issue. Thank you!
