### ISSUE TITLE
Is it possible to have infinite scollable ?

### ISSUE THREAD

**Issue by ronak301** [react-native-community/react-native-tab-view#13]
It is my case that i have dozens of tabs , is it possible to have infinite scrolling top tab bar.

**Comment by satya164** [comment]
If you mean just scrollable tabbar, it's possible, but we don't have a component for it yet. If you want to help implementing it, ping me :)

**Comment by npm-install** [comment]
@ronak301 @satya164  Were you able to do proof of the concept on this? Got some suggestion to use `ScrollView` which I am going to give a try.

**Comment by satya164** [comment]
@npm-install Nope. But yeah, I think `ScrollView` is the way to go. Here is what I was thinking,

1. By default give each of the tabs the width - `(layout.width / 3) * 2`, so that the third tab is partially visible, also allow a custom `tabItemWidth` prop
2. When a tab is focused, animate (`scrollTo`?) the tabbar item to center of the screen (we'll need to calculate this)
3. Ensure the scrollbars are hidden

**Comment by knowbody** [comment]
this is something that I will need very soon, so can help on that if there is work already done on it or I might start separately

**Comment by satya164** [comment]
I'm working on this right now and it's a bit complex than thought, if we want smooth animations. Will keep you updated.

It needs a lot of maths and I'm poor at maths. Help is much appreciated :D

**Comment by satya164** [comment]
Here's a PR which implements it. Testing and feedback is appreciated - https://github.com/react-native-community/react-native-tab-view/pull/32

**Comment by knowbody** [comment]
so far so good, testing...
