### ISSUE TITLE
How to jump to the Third tab without loading second tab

### ISSUE THREAD

**Issue by keerthanarbt** [react-native-community/react-native-tab-view#147]
Hi,
  We are trying to click third tab but its loading the second tab (which has API call)and moving to the third tab.
I want to move directly to corresponding tab which i clicked without loading other page..

**Comment by smart-mickey** [comment]
You can initate index of navigationstate in constructor function like below:
this.state = { 
            navigationState: {
              index:  2,
              routes: [
                { key: '0', title: 'screen0' },
                { key: '1', title: 'screen1' },
                { key: '2', title: 'screen2 },
                ...
              ],
            },
            ...
        };

**Comment by aravindhrbt** [comment]
Hi @smart-mickey ,

 I also need assistance in this situation,
my case is i have 
```
state = {
    index: 0,
    routes: [
      { key: '1', title: 'page 1' },
      { key: '2', title: 'page 2' },
      { key: '3', title: 'page 3' },
    ],
  };
```

and each page have api call to get data in componentDidMount()

so by default i will land on page 1 and get data for the respective page
i also included 

> lazy

so that the page loads when requested( got help from this [#96](https://github.com/react-native-community/react-native-tab-view/issues/96)),

**my question is** 
_by default my page 1 is loaded, and if i try to go to page 3 directly it makes api call in page 2 (i.e page 2 componentDIdMount is called) and also in page 3 and renders page 3

this makes unwanted api call that is not needed at that point of time.

is there any way to load page 3 directly on click._

**Comment by cbjs** [comment]
i don't know if it's the best solution,

render nothing while index of route is not same with state.index.
```js
_renderScene({route, index}) {
     return index == this.state.index ? <YourPage key={route.key}/> : null;
}
```

still has some problems here. while switching tabs, blank page flashed even when page is loaded.
so i write a PageWrapper

```js
class PageWrapper extends Component {
  constructor(props) {
    super(props);
    this.state = { loaded : props.active }
  }

  componentWillReceiveProps(nextProps) {
    if (nextProps.active && !this.state.loaded) {
      this.setState({loaded: true})
    }
  }

  render() {
    const { active, children } = this.props;
    return active || this.state.loaded ? <View style={{flex: 1}}>{children}</View> : null;
  }
}

...
  _renderScene = ({route, index}) => {
    return <PageWrapper active={index == this.state.index}>
      <YourPage key={route.key}/>
    </PageWrapper>;
  }
```

hope it helps.

**Comment by aravindhrbt** [comment]
Thanks alot @cbjs  💯  👍 

This work around gave solution for my scenario..thanks again..
