### ISSUE TITLE
<TabBar /> pressColor  not working

### ISSUE THREAD

**Issue by leoaccorsi** [react-native-community/react-native-tab-view#180]
is it right?

```
<TabBar
  tabStyle={{backgroundColor: '#f7941e', height: 35}}
  pressColor="#000"
  labelStyle={{color: '#000', fontSize: 12}}
  {...props}
/>
```

when i press, the pressed color isn't black is blue.

Is my code wrong?

**Comment by CharlesMangwa** [comment]
Hi @leoaccorsi! Your code is ok, no worries. I think you're facing this issue on iOS only if I'm not mistaken. This is because RNTB use 2 different RN touchables in `<TabBar />` ([as you can see here](https://github.com/react-native-community/react-native-tab-view/blob/master/src/TouchableItem.js#L43-L62)):
- `TouchableNativeFeedback` on Android (which accepts a `pressColor` prop)
- `TouchableOpacity` on iOS (which doesn't)

Thus, you just need to add `pressOpcity={1}` to your `<TabBar />` so that you won't see the blue background on iOS. Here is a working example, feel free to re-opened this issue if needed: https://sketch.expo.io/SymWdeBhl.
