### ISSUE TITLE
How to implement modal with tab view

### ISSUE THREAD

**Issue by prtkkmrsngh** [react-native-community/react-native-tab-view#242]
I'm using [react-native-modalbox](https://github.com/maxs15/react-native-modalbox). Nesting `react-native-modalbox` component and `TabViewAnimated` is not working. Using modal inside scenes doesn't overlay the entire screen, tab can be switched. Any help?

**Comment by satya164** [comment]
The library doesn't use Portals, so it's expected. It's not specific to tab view.

**Comment by prtkkmrsngh** [comment]
Fixed it by modifying library. Used RN Modal https://github.com/prtkkmrsngh/react-native-modalbox

**Comment by askarhu** [comment]
@prtkkmrsngh Can you please share what you modified. I'm running into the same issue with tabbed views and struggling to get this to work as it always get tucked as the last component within the view heirarchy and not covering the entire viewport. Not sure if I can just npm i your library instead of the original one. Would appreciate if you can please chime in.

**Comment by prtkkmrsngh** [comment]
@askarhu You can use [https://github.com/prtkkmrsngh/react-native-modalbox](https://github.com/prtkkmrsngh/react-native-modalbox) repo, PR to cover screen is merged over there and can be used with react-native-tab-view.

**Comment by satya164** [comment]
We recently released a library which also has a modal component that you can use https://callstack.github.io/react-native-paper/modal.html
