### ISSUE TITLE
Varying tab width

### ISSUE THREAD

**Issue by yayanartha** [react-native-community/react-native-tab-view#256]
How to produce a different tab width regarding to length of the tab label like the image below. And how can I make the indicator bar length align with the label?
![screen shot 2017-05-19 at 3 26 39 pm](https://cloud.githubusercontent.com/assets/10683719/26237550/32de3a64-3ca8-11e7-9bda-aca387d03de5.png)

**Comment by CharlesMangwa** [comment]
Hi @yayanartha! I'll suggest you to have a look at one of the examples provided in the repo, and tweak the [`renderHeader()` method](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarTextExample.js#L37-L48) as you wish. 

You can check out how tabviews' length are handle in TabBar [right here](https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.js#L166-L214).

If you face any bug working on this, let us know by re-opening this issue and providing your code on [Expo's Snack](https://snack.expo.io) if you can, so that we'll be able to help you!

**Comment by yayanartha** [comment]
No, I mean different width for each tab. Say I have 4 tabs, each width is different. Can it be?

**Comment by satya164** [comment]
It's not possible right now since it's a bit complex to do. PRs welcome.

**Comment by code-smith** [comment]
@satya164 Great work! Hi, i've read your blog on medium and i'm currently using this component. 
I'm sure you agree things can be improved and that's what the community is for. 
From What i read in the blog , you mentioned that you were trying to build it as per material guidelines but not having dynamic tab width in tabbar is really a big feature to miss out.
I would request you to please take this feature as a priority and work on this.
Hope you consider the request and spend some time on it.
I myself will try making a PR this weekend. 
Thanks.

**Comment by Aryk** [comment]
Hey guys...just curious if this is now possible to do? It's been three years so maybe I'm missing an update.
