### ISSUE TITLE
Smaller tab menu

### ISSUE THREAD

**Issue by hyochan35** [react-native-community/react-native-tab-view#259]
<img width="244" alt="2017-05-21 1 19 31" src="https://cloud.githubusercontent.com/assets/20625109/26281643/90ac6de6-3e38-11e7-9829-d76c2612365d.png">

I want to design tab view with smaller size like image above.
When I do that child views get smaller also.
I want child views to fit the width of parent and want only smaller sized tab menu.

How can I concur?

**Comment by CharlesMangwa** [comment]
Hi @hyochan35: you just have to use one of the examples provided in the repo, and tweak the `[renderHeader method](https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarTextExample.js#L37-L48)` as you wish. 

You can have a look at how tabviews' length are handle in TabBar [right here](https://github.com/react-native-community/react-native-tab-view/blob/master/src/TabBar.js#L188-L214).

If you face any bug working on this, let us know by re-opening this issue and providing your code on [Expo's Snack](https://snack.expo.io) if you can, so that we'll be able to help you!
