### ISSUE TITLE
tabs animation with dynamic data

### ISSUE THREAD

**Issue by yotavm** [react-native-community/react-native-tab-view#372]
hi,
I start using this model 
I'm using it for dynamic tabs and content 
![screen shot 2017-10-26 at 1 45 27 pm 1](https://user-images.githubusercontent.com/11390250/32049010-11e19c1e-ba54-11e7-957a-373942852eb1.png)

I have a dynmic number of tabs and ever body is a list view
so you can scroll the tabs for more

my problem is that every time I open the page with the tabs 
my indicator stack even if I move between tabs with swipe and after same time it's going back to work

code 
https://gist.github.com/yotavm/45c91e14694bdbd1ad2464186fa9be92

full gif with the problem

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/11390250/32050148-7b5baabe-ba58-11e7-92fa-31fbfe482704.gif)

**Comment by satya164** [comment]
That's currently a bottleneck due to the fact that it's quite complicated to offload animations to native when you have to support 2 platforms with 2 different APIs. It should be better in production.

I'm currently working on an alternative implementation with the same API using https://github.com/kmagiera/react-native-gesture-handler which will fix the issue.

**Comment by yotavm** [comment]
this gif is from the device 
you can explain what makes the problem?

**Comment by yotavm** [comment]
there is way to use your alternative or it will take time?

**Comment by satya164** [comment]
The JavaScript thread is blocked due to the setState while the swipe is happening. The indicator animation happens in JS and gets blocked as a result, while the swipe animation runs in the native thread.

In it's current state, the alternative implementation doesn't support scrollable tabs. So you won't be able to use it. It'll take some time before it's done.

**Comment by yotavm** [comment]
you have an idea how can i work around this or hack for now?

**Comment by satya164** [comment]
make sure all your individual screens are pure components. see https://github.com/react-native-community/react-native-tab-view#optimization-tips
