### ISSUE TITLE
Why lazy prop has been dropped out?

### ISSUE THREAD

**Issue by douglasjunior** [react-native-community/react-native-tab-view#406]
Why lazy prop has been dropped out? https://github.com/react-native-community/react-native-tab-view/commit/28457e6350d10bfefa49afeaa981418021181122

**Comment by quy1403** [comment]
@satya164 the same question, and how can I render other page when the other tab is pressed? Thanks

**Comment by satya164** [comment]
I mentioned in [react-navigation#3064](https://github.com/react-community/react-navigation/pull/3064), but I'll repeat it:
- It didn't work great with more than 2 tabs
- It's not very performant to listen to all events during the gestures since we're trying to move away towards native gestures.
- It basically triggered a re-render of the whole tab view mid-gesture, which could cause jank

> how can I render other page when the other tab is pressed

You have access to the navigation state, conditionally render your pages when the state changes.
