### ISSUE TITLE
renderScene is called multiple times while tab change for all the tabs

### ISSUE THREAD

**Issue by Louies89** [react-native-community/react-native-tab-view#532]
Dear @satya164 ,
I am developing android application,
In this I have 3 tabs, and my code is as below:

```
this.state = {
	index: 1,
	routes: [
		{ key: 'tab1', title: 'TAB1' },
		{ key: 'tab2', title: 'TAB2' },
		{ key: 'tab3', title: 'TAB3' }]
}
      
<TabViewAnimated
   navigationState={this.state}
   onIndexChange={this._handleIndexChange}
   initialLayout={initialLayout}
   renderHeader={this._renderHeader}
   renderScene={this.renderScene}
/>

_renderHeader = props => (
  <TabBar
  	{...props}
  	scrollEnabled
  	indicatorStyle={styles.indicator}
  	style={{ backgroundColor: HEXCOLOR.pColor, height: this.state.showsearch ? 0 : 50 }}
  	tabStyle={styles.tab}
  	labelStyle={styles.label}
  	useNativeDriver={true}
  />
);

renderScene = ({ route }) => {
switch (route.key) {
  alert(route.key)
  case 'tab1':
	  return (
		<TAB1/>
	  )
  case 'tab2':
	  return (
		<TAB2/>
	  )
  case 'tab3':
	  return (
		<TAB3/>
	  )
  default:
	return null;
  }
}
```

If you see above code, the **alert()** inside **renderScene** is getting called multiple times with different values of **route.key**.

Which means different tabs are getting rendered each time any tab change occurs.

This is a serious issue and please check this.

Thank you for the beautiful library.. :)

**Comment by satya164** [comment]
They won't re-render if you use `SceneMap` which is in the default example. If you need to use `renderScene`, you can optimize it yourself by using `PureComponent`: https://github.com/react-native-community/react-native-tab-view#avoid-unnecessary-re-renders

**Comment by Louies89** [comment]
Those things I have seen, but, my point is why all the tabs are re rendered, when I am switching tab.

And if this shall be solved then the use of PureComponent is not required.

And sometimes we have to update component and when things are complex, if we use PureComponent,
a lot of work has to be done.

So I think if this can be solved, then it will be helpful to many programmers.

**Comment by satya164** [comment]
Because that's how React works. The navigation state in the parent updates, which re-renders it's children. Not doing that is way more confusing. The quick start example is the most performant way. If you drop down to custom function for `renderScene`, the optimization is left up to you. I think it's clearly documented. If you think there's something confusing in the docs, PR is welcome.

> And sometimes we have to update component and when things are complex, if we use PureComponent, a lot of work has to be done.

I don't see how PureComponent affects it? If you need to update the component, you pass a prop. Pure component shouldn't affect anything at all or make anything harder as long as you're doing things the React way and not relying on mutations and side effects.

**Comment by Louies89** [comment]
Ok,understood your point...
Thank you :)
