### ISSUE TITLE
a setState during a tab transition will cause a jump

### ISSUE THREAD

**Issue by gre** [react-native-community/react-native-tab-view#55]
with current way shown in the example, it looks like I have to **control** the tab ~ like this:

```
  onRequestChangeTab={this._handleChangeTab}
...
_handleChangeTab = (index) => this.setState({ index })
```

the problem I see is that _handleChangeTab is always called AFTER the transition is done, but not "before" , and the problem is if one setState happen **or any tree update**, the render() get called again with the **previous tab index** which causes a jump.

I have tried `0.0.37` as well as `master`. Both have the problem.

**Comment by satya164** [comment]
> with current way shown in the example, it looks like I have to control the tab ~ like this:

Yeah, you own the navigation state.

> the problem I see is that _handleChangeTab is always called AFTER the transition is done, but not "before" 

This is a deliberate choice made to keep the transitions smooth. `setState` will trigger React's reconciliation algorithm which can cause jank when gesture is starting. Also we really don't know which tab you'll settle on until the transition is done, since you could be swiping quickly before stopping on your desired tab.

> and the problem is if one setState happen or any tree update, the render() get called again with the previous tab index which causes a jump.

I think we should be able to handle it by changing,

```js
componentDidUpdate() {
  this._transitionTo(this.props.navigationState.index);
}
```

to

```js
componentWillReceiveProps(nextProps) {
  if (nextProps.navigationState.index !== this.props.navigationState.index {
     this._transitionTo(nextProps.navigationState.index);
  }
}
```
