### ISSUE TITLE
Frame drops when switching tabs

### ISSUE THREAD

**Issue by jephtta** [react-native-community/react-native-tab-view#76]
When the app starts, i make some api calls  for data to update the UI in 3 (out of 5) of the tabbed components.
Now if an attempt to switch tabs coincides with the exact moment the UI within any of the tabs is being updated, there is a very obvious drop in frames, and stuttering in the tab switching animation.
Any advice on how to eliminate these?

**Comment by satya164** [comment]
It's not possible since JS is single threaded. Until the ongoing work on native animations is done, we don't have much luck.

You could try few things though,

1) Defer updating the UI until the interaction is finished through `InteractionManager` - https://facebook.github.io/react-native/docs/performance.html
2) You can try using `<TabViewPagerScroll />` on iOS and `<TabViewPagerAndroid />` on Android, it'll make swiping smoother, but the indicator animation will still drop frames - https://github.com/react-native-community/react-native-tab-view#tabviewpagerscroll-

**Comment by jephtta** [comment]
Thanks @satya164 . Was actually holding off using InteractionManager until i heard your input. Thought I was doing something wrong. Will close this after a while if there are no more inputs.

**Comment by satya164** [comment]
👍
