### ISSUE TITLE
add isRTL prop instead of using i18nManager.isRTL

### ISSUE THREAD

**Issue by Amenocy** [react-native-community/react-native-tab-view#825]
hi 
I think it is better to add a new prop "isRTL" for RTL support instead of using i18nManager,
in my use case, I want to disable RTL support in my tab bar but I cant and I had to fork the repo and change code directly.
if you use props, we can pass i18nManager or another flag to it and there is no difference at all but much more flexibility.

**Comment by satya164** [comment]
> I think it is better to add a new prop "isRTL" for RTL support instead of using i18nManager

I wish it was that easy. The native components already handle RTL and our calculations become incorrect due to this, resulting in broken layout. The checks we have don't just add support for RTL mode, they are necessary not to have a broken tab bar in RTL. These bugs may not be visible if you don't have `scrollEnabled` set to `true`.

> I had to fork the repo and change code directly

You don't have to fork the repo, you can copy the code for the tab bar or write a custom tab bar with the behaviour you want and use `renderTabBar`.
