### ISSUE TITLE
Active tab indicator "janky" with width auto when using gestures to switch tabs

### ISSUE THREAD

**Issue by tomkelsey** [react-native-community/react-native-tab-view#847]
Just want to say this is awesome and so is the recent addition to accommodate automatic tab widths. Apologises for the use of "janky" I just wanted to highlight it wasn't quite as nice as the rest of the experience :)

### Current behaviour

- Use tab width "auto" on a MaterialTopTabNavigator
- Run the code in iOS simulator
- Tapping between tabs works as expected
- Swiping between tabs the active tab indicator doesn't expand/shrink to the correct size until the last moment which looks quite jarring.

### Expected behaviour

That the tab indicator more smoothly adjusts to the correct size (like it does when you tap a tab) or if that isn't possible an option to disable the tab indicator animation.

### Code sample

I believe the behaviour is exhibited in a standard example with tab width set to "auto"

### Screenshots (if applicable)

N/A

### What have you tried

N/A

### Your Environment

| software                     | version
| ---------------------------- | -------
| ios or android               | ios
| react-native                 | 0.60.3
| react-native-tab-view        | 2.9.0
| react-native-gesture-handler | 1.3.0
| react-native-reanimated      | 1.1.0
| node                         | 10.15.3
| npm or yarn                  | yarn

**Comment by satya164** [comment]
Can you provide a video/gif and a runnable repro?

**Comment by ianwelsh** [comment]
We are experiencing this as well. Android seems worse than iOS. See attached zip file for reproducible project (excludes ios & android directories in order to fit in to Github's file limits, I can upload full project to Google Drive and link if necessary). [jankyTabs.zip](https://github.com/react-native-community/react-native-tab-view/files/3506044/jankyTabs.zip)

Video showing issue here, https://drive.google.com/file/d/1w39jOy869LmUojC3x7F16TfmSui9qQXS/view?usp=sharing. There is also a large delay between pressing the tab and the UI rendering tab change, as you can see in the video. Video is taken on physical android device using command `react-native run-android --variant=release`.

**Comment by ludwig-adoria** [comment]
Same behaviour with tab indicator here
connected issue here #866

**Comment by ludwig-adoria** [comment]
Ok ! I have fix this issue by upgrade react-native-tab-view to  "^2.10.0"
( i had the old one 2.0.1.... ).

thanks for the amazing job boys !

**Comment by ludwig-adoria** [comment]
OK i think i have find a solution to avoid this problem !

At the begining i was using severals "hooks" like useSelector ( with redux ) inside my tabView's container & some data manipulation to create dynamically my navigationState.

it's created performance issues... So i was try to useMemo to avoid it and memoize heavy calculations but it's didn't work.

Finally, i moved the code of my hooks selectors & make my data manipulation before my tabView wrapper did mount. => Solve

**Comment by fitranto** [comment]
i have a similar problems
its strange, the issue self fixed just by stop the expo and run with `expo r -c`

**Comment by fitranto** [comment]
i have a similar problems,
its strange that i need to stop remote debugging on expo go and the issue self fixed.
