### ISSUE TITLE
Indicator does not stick to the currently selected tab when scrolling

### ISSUE THREAD

**Issue by bevkoski** [react-native-community/react-native-tab-view#89]
When using a ```TabBarTop``` with ```scrollEnabled``` the indicator for the selected tab demonstrates strange behaviour. When scrolling inside the tab bar, the indicator does not remain fixed to the currently selected tab. Instead, it moves a bit along the scrolling direction before settling into the correct position.

It can be reproduced using one of the examples provided (https://github.com/react-native-community/react-native-tab-view/blob/master/example/src/TopBarTextExample.js). It can also be noticed in the GIF below.

![non-sticky-indicator](https://cloud.githubusercontent.com/assets/6344196/21481397/750ed1d0-cb67-11e6-8c07-5a74ffe4d4b3.gif)

**Comment by satya164** [comment]
Due to the way it's implemented, it's impossible to make it follow the scroll, at least not until we can implement native animation events. It's more important to have good frame rates for the indicator rather than making it follow the scroll. Perhaps one day we'll be able to change the implementation to make it follow the scroll properly without having to sacrifice on frame rate. But it's still a long way to go. I think the current behaviour is good enough since we avoid anything abrupt and animate the indicator nicely.
