### ISSUE TITLE
renderScene method render to many times. and content is the webview, can`t scroll

### ISSUE THREAD

**Issue by xclidongbo** [react-native-community/react-native-tab-view#947]
renderScene method render to many times. and content is the webview, can`t scroll

**Comment by quixote15** [comment]
I am experiencing a similar problem with renderScene. I have a tab with three routes just like the example on readme:

    const renderScene = SceneMap({
       first: FirstRoute,
       second: SecondRoute,
       third: ThirdRoute,
     });

The problem is that each route is a component that loads some content when it mounts:

     useEffect(() => {
       loadSomeListItems()
      }, []);

The component then keeps rerendering and therefore loading data too many times and since I have some background images, those images start blinking.


Do you guys have any solution yet?

**Comment by Djunnni** [comment]
@quixote15 
it's work like componentDidMount() 
[example link](https://medium.com/@felippenardi/how-to-do-componentdidmount-with-react-hooks-553ba39d1571) 
~~~
 useEffect(() => {
   loadSomeListItems()
  }, []);
~~~
--------------
@xclidongbo 
i also had this problem but i needed just tab view. 
but functional Component  is not easy to me like useEffect 
how about using 'react-navigation-tabs' ?😄
it's also work like tab-view 
i referred to [youtube](https://www.youtube.com/watch?v=hWMn32erJ2g)
it's simple and more compact
